const Data = [
         {
            'id':'1',
            'name':'Jaipur',
            'url' : 'https://media.cntraveller.in/wp-content/uploads/2014/02/Jal-Mahal-Jaipur-123rf-2-866x487.jpg',
            'description' : 'Jaipur is the capital of India’s Rajasthan state. It evokes the royal family that once ruled the region and that, in 1727, founded what is now called the Old City, or “Pink City” for its trademark building color. At the center of its stately street grid (notable in India) stands the opulent, colonnaded City Palace complex. With gardens, courtyards and museums, part of it is still a royal residence.',
            'places':[
               {
                  'name':'Hawa Mahal',
                  'description':'asdsdsa',
                  'images':[
                     {
                        'url':''
                     },
                     {
                        'url':''
                     },
                     {
                        'url':''
                     }
                  ],
                  'coordinates':{
                     'lon':145.77,
                     'lat':-16.92
                  }
               },
               {
'name':'Hawa Mahal',
                  'description':'asdsdsa',
                  'images':[
                     {
                        'url':''
                     },
                     {
                        'url':''
                     },
                     {
                        'url':''
                     }
                  ],
                  'coordinates':{
                     'lon':145.77,
                     'lat':-16.92
                  }
               },
               {
'name':'Hawa Mahal',
                  'description':'asdsdsa',
                  'images':[
                     {
                        'url':''
                     },
                     {
                        'url':''
                     },
                     {
                        'url':''
                     }
                  ],
                  'coordinates':{
                     'lon':145.77,
                     'lat':-16.92
                  }
               }
            ]
         },
         {
            'id':'2',
            'name':'Delhi',
            'url' : 'https://cdn.britannica.com/s:700x450/37/189837-004-1EE26D5A.jpg',
            'description': 'Delhi, India’s capital territory, is a massive metropolitan area in the country’s north. In Old Delhi, a neighborhood dating to the 1600s, stands the imposing Mughal-era Red Fort, a symbol of India, and the sprawling Jama Masjid mosque, whose courtyard accommodates 25,000 people. Nearby is Chandni Chowk, a vibrant bazaar filled with food carts, sweets shops and spice stalls',
            'places':[
               {
                  'name':'Hawa Mahal',
                  'description':'asdsdsa',
                  'images':[
                     {
                        'url':''
                     },
                     {
                        'url':''
                     },
                     {
                        'url':''
                     }
                  ],
                  'coordinates':{
                     'lon':145.77,
                     'lat':-16.92
                  }
               },
               {
'name':'Hawa Mahal',
                  'description':'asdsdsa',
                  'images':[
                     {
                        'url':''
                     },
                     {
                        'url':''
                     },
                     {
                        'url':''
                     }
                  ],
                  'coordinates':{
                     'lon':145.77,
                     'lat':-16.92
                  }
               },
               {
'name':'Hawa Mahal',
                  'description':'asdsdsa',
                  'images':[
                     {
                        'url':''
                     },
                     {
                        'url':''
                     },
                     {
                        'url':''
                     }
                  ],
                  'coordinates':{
                     'lon':145.77,
                     'lat':-16.92
                  }
               }
            ]
         },
         {
            'id':'3',
            'name':'Chennai',
            'url': 'https://www.skymetweather.com/content/wp-content/uploads/2018/03/Chennai-1.jpg',
            'description': 'Chennai, on the Bay of Bengal in eastern India, is the capital of the state of Tamil Nadu. The city is home to Fort St. George, built in 1644 and now a museum showcasing the city’s roots as a British military garrison and East India Company trading outpost, when it was called Madras. Religious sites include Kapaleeshwarar Temple, adorned with carved and painted gods, and St. Mary’s, a 17th-century Anglican church.',
            'places':[
               {
                  'name':'Hawa Mahal',
                  'description':'asdsdsa',
                  'images':[
                     {
                        'url':''
                     },
                     {
                        'url':''
                     },
                     {
                        'url':''
                     }
                  ],
                  'coordinates':{
                     'lon':145.77,
                     'lat':-16.92
                  }
               },
               {
'name':'Hawa Mahal',
                  'description':'asdsdsa',
                  'images':[
                     {
                        'url':''
                     },
                     {
                        'url':''
                     },
                     {
                        'url':''
                     }
                  ],
                  'coordinates':{
                     'lon':145.77,
                     'lat':-16.92
                  }
               },
               {
'name':'Hawa Mahal',
                  'description':'asdsdsa',
                  'images':[
                     {
                        'url':''
                     },
                     {
                        'url':''
                     },
                     {
                        'url':''
                     }
                  ],
                  'coordinates':{
                     'lon':145.77,
                     'lat':-16.92
                  }
               }
            ]
         }
      ];

      export default Data;
